### ISSUE TITLE
Account name and amount in header are blinking when navigating

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-wallet#107]
When I go to different page in wallet header is blinking for a little moment (I assume while it's loading account data from node). Probably shouldn't blink when there is already data loaded from server.
Maybe there should be some very subtle indication of data loading (something like pulsating dot, definitely not full-blown spinner).

**Comment by marcinbodnar** [comment]
OK, I will handle it.

Also, we are using this loader in many other places, maybe you would like to change it something else? We can use something like on github when small loader bar appears on top. Or a similar solution?

**Comment by vgrichina** [comment]
> We can use something like on github when small loader bar appears on top. Or a similar solution?

yes, I think something global and subtle like this is best match for most cases, but we need to sync with Jake on specifics

**Comment by kcole16** [comment]
Closed by #107
