### ISSUE TITLE
shell integration: after adding the key for shell, it does not show in apps list 

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-wallet#110]
See screenshot after authorizing near shell:
<img width="1356" alt="Screen Shot 2019-07-19 at 3 23 45 PM" src="https://user-images.githubusercontent.com/1320689/61568724-3f196f00-aa39-11e9-9858-970811c6d2a1.png">

**Comment by vgrichina** [comment]
that's cause non-app specific keys don't get returned by RPC in nearcore

**Comment by janedegtiareva** [comment]
We can now get all keys in one query (http post https://rpc.nearprotocol.com/ method=query jsonrpc=2.0 params:='["access_key/{accountId}", ""]' id=123). This is probably a wallet-only fix now.

**Comment by vgrichina** [comment]
AFAIK full access keys are displayed since https://github.com/nearprotocol/near-wallet/pull/151 landed
