### ISSUE TITLE
UI for Key Management + revoking keys + recovering keys

### ISSUE THREAD

**Issue by ckshei** [nearprotocol/near-wallet#119]
We should discuss whether or not we would like to have some UI which allows users to see and manage all the key pairs associated with an account. 

Also good to discuss what the ideal behavior would be when someone loses their key and recovers it. Currently, if someone loses their key, we'll link a new public key onto their account, but the previous key pair is still associated with the account. If we offer the ability to manage key pairs, the user can decide whether or not to revoke the lost key pair or to keep it active.

**Comment by vgrichina** [comment]
We likely need to extend existing Authorized Apps UI to also include non-app keys. Makes sense to do after related refactoring lands in nearcore.

**Comment by vgrichina** [comment]
MVP landed https://github.com/nearprotocol/near-wallet/pull/151
