### ISSUE TITLE
Create account: "Username is taken" when entering any name followed by ".near"

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#136]
When creating an account, appending ".near" to any name will result in "Username is taken. Try something else". [Video](https://drive.google.com/file/d/1jQAhOoc1qpfnUF9hKeyo2q_VoS37MF3Z/view?usp=sharing)

As the placeholder text is "example: satoshi.near", this may lead to confusion for the user.

**Comment by bowenwang1996** [comment]
I think the error message needs to be fixed. The problem here is that you cannot create an account with some domain name like `near` from an account other than `near`.

**Comment by vgrichina** [comment]
Why this got closed? It's still and issue, we need to fix error handling.

It's currently blocked by `nearcore` coming up with alternate solution to https://github.com/nearprotocol/NEPs/pull/11
This is AFAIK currently on @mikhailOK

**Comment by kcole16** [comment]
Closing as this is a dupe of the more relevant #289
