### ISSUE TITLE
Manual Account Recovery

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#153]
## Story

As a developer testing my app workflow with the Wallet, I want to easily recover my account without entering my phone number, so I can quickly test my app in different browsers/devices without access to SMS.

## Acceptance Criteria

- [ ] User can download keystore file during account creation
- [ ] User can select keystore file using file picker to recover account
- [ ] User's key is correctly stored in localStorage post file upload
- [ ] File upload works correctly on Chrome, Firefox, and Safari
- [ ] Tested

## User Flow
**Setup Manual Recovery**
- On "/create", user enters a .near name, clicks "Create Account"
- User selects "I choose to backup my account manually", initiates download of JSON file (keystore.json) with the following:

```
{  "nearlib:keystore:<username>:default" : "<key>" } 
```
- User is redirected to home page (/)

**Recover Account Manually**
- On "/create", user selects "Recover account manually with keystore file"
- File picker opens, user selects keystore file 
- Key stored in localStorage, user is redirected to home page (/)

## Manual Recovery Copy:
"Skip this step if you would like to recover your account manually. This method is considered INSECURE, and should only be used for testing purposes. The following link will download a keystore file to your device, which you must save in order to recover your account in the future."

**Comment by kcole16** [comment]
@vgrichina @jakestutzman Thoughts on this as a very simple manual recovery flow?

**Comment by deacix** [comment]
Hey guys! You should maybe take a look to https://www.w3.org/TR/WebCryptoAPI/.
Private key shouldn't be stored in localStorage or IndexDB of the browser..
