### ISSUE TITLE
Introduce CI & CD for NEAR wallet

### ISSUE THREAD

**Issue by deacix** [nearprotocol/near-wallet#154]
## Story

As a developer who is working on near-wallet project, I want to see running tests in Github Actions CI so I can verify that what i committed is valid and working.

## Acceptance Criteria

- [ ] Github Action workflow file is written and pushed
- [ ] Is tested

## NOTES

- An implementation in near-explorer is already existing and merged in to the master branch

**Comment by frol** [comment]
CI is setup via GitLab. CD is setup via Render.com. NEAR Wallet is good on this scale, I would say.
