### ISSUE TITLE
no favicon

### ISSUE THREAD

**Issue by azban** [nearprotocol/near-wallet#16]

**Comment by eriktrautman** [comment]
Specifically, icons on the other NEAR properties are updated but this one is not
![image](https://user-images.githubusercontent.com/2977438/58376146-29e00280-7f18-11e9-89b9-865ae6dd47ea.png)

**Comment by eriktrautman** [comment]
From @jakestutzman 
![](https://cdn.discordapp.com/attachments/520295065835274250/582157339050770444/wallet_icon.png)
