### ISSUE TITLE
Example wallet account name with .test misleading

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-wallet#164]
When signing up for testnet, the user has to set a Username. Currently, the example shows satoshi.test

As far as I understand, it should be a name without the . 

If that's the case, provide a different example and Username specifications e.g. what characters are allowed.

**Comment by kcole16** [comment]
We're planning to rework this flow. Currently, names followed by .test work, while any other names with . will show "Username is taken". This issue is related to https://github.com/nearprotocol/near-wallet/issues/136

**Comment by kcole16** [comment]
Closing as this is better explained re: mainnet in #344
