### ISSUE TITLE
[Safari] Verify and switch to use cookies instead of localStorage

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/near-wallet#18]
It seems safari properly respects default privacy settings only with cookies. Currently safari still sandboxes iframes of the wallet for localStorage even if have visited the website before this. But cookies seems to be passed through to the iframe. So we may consider switching to cookie storage on wallet side. Cookies will only be visible to the `wallet.nearprotocol.com`.
The issue is the security of the data will be accessible to the server-side. Need to think more about this, but one option is to encrypt keys stored in cookies with the application token. So whenever wallet is accessed by the application, it always provides the token. We can decrypt cookies with this token and sign transaction. In this case, if we never expose token to the server-side, it would be somewhat secure, while still not ideal.

**Comment by vgrichina** [comment]
Deprecated as wallet now supports access keys
