### ISSUE TITLE
Google APIs don't work in China

### ISSUE THREAD

**Issue by eriktrautman** [nearprotocol/near-wallet#20]
via @ilblackdragon :
On GuestBook/Wallet frontend somehow jquery from googleapis was added (T https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js net::ERR_CONNECTION_RESET) which doesn't work in China.
It wasn't there a week ago - can we not use google CDN?
or this is google analytics?
it's not loading broke all JS on the page - so "Login with Wallet" didn't work at the demo :frowning:

**Comment by ilblackdragon** [comment]
Fixed.
