### ISSUE TITLE
Add banner to indicate current network (Testnet, Betanet, etc)

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#208]
## Story
As a user, I want to know which network I'm using, so I can determine if the assets and activity are permanent and valuable, or just for demo purposes.

## Acceptance Criteria
- [ ] Banner shown at the top of the screen: "You are using the NEAR TestNet. The accounts you create will not exist on Mainnet, and the tokens and assets have no value."

[Banner Mockup](https://drive.google.com/file/d/11eJN6UNWZGgWM5M856Rq7leqlcSby2zA/view)

**Comment by kcole16** [comment]
@corwinharrell Bumping this up the priority list, as we're starting to have users from beta program apps trying out the wallet (e.g. Flux). 

We want to clearly indicate to users that they are using the Testnet, not Mainnet, and that all balances are Test NEAR.

**Comment by corwinharrell** [comment]
@kcole16 np this should be a quick one 👍

**Comment by vgrichina** [comment]
@kcole16 let's stop using `Priority 0` for stuff which isn't "drop everything else", otherwise we won't have any priority level for stuff which actually requires dropping everything.

**Comment by frol** [comment]
There is currently a label "TESTNET" on the top bar, but it is not really visible, and it is incorrectly stating TESTNET even on DEVNET and BETANET instances.

**Comment by corwinharrell** [comment]
@kcole16 assuming this carry over to the explorer as well? 🤔

**Comment by Patrick1904** [comment]
@kcole16 @corwinharrell @vgrichina: first take on [network banner design](https://www.figma.com/proto/VgHyW8zjZ8g4Y3sAXFb9bj/Testnet-banner?node-id=7%3A5&viewport=-1403%2C532%2C0.8478490710258484&scaling=min-zoom)

**Comment by kcole16** [comment]
Would almost err on the side of making it slightly larger, with an even more contrasting color (though the blue does a pretty good job of this).

**Comment by Patrick1904** [comment]
> Would almost err on the side of making it slightly larger, with an even more contrasting color (though the blue does a pretty good job of this).

@kcole16 I agree. Size may look smaller because of the zoomed out view in Figma but we can play with size when implemented. I've added a few more color variations to the prototype.

**Comment by Patrick1904** [comment]
I feel like [modal](https://www.figma.com/proto/VgHyW8zjZ8g4Y3sAXFb9bj/Testnet-banner?node-id=57%3A1&viewport=-1403%2C532%2C0.8478490710258484&scaling=min-zoom) is more appropriate/best practice for mobile. Adds a bit more scope. Thoughts?

@kcole16 @jakestutzman @vgrichina @corwinharrell

**Comment by kcole16** [comment]
Modal on both is a good idea, but I see it as more of an addition, rather than a substitution. (likely a separate issue)

**Comment by Patrick1904** [comment]
> Modal on both is a good idea, but I see it as more of an addition, rather than a substitution. (likely a separate issue)

@kcole16 not sure I understand what you mean? Why would it be addition?

**Comment by kcole16** [comment]
Ah, missed the designs link!

I think the modal works well if it's on desktop and mobile, especially if that's more straightforward implementation.

**Comment by corwinharrell** [comment]
Just jumping in here quickly to vote both/and for banner + dismiss-able modal.
