### ISSUE TITLE
Google Analytics events no longer tracking

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#210]
We haven't received any new events in GA since [Thursday, Oct 24](https://analytics.google.com/analytics/web/?authuser=1#/report/content-event-overview/a100373569w209375678p201575861/)

Might be related to [this commit](https://github.com/nearprotocol/near-wallet/commit/3522abe67c8987b950b1cf9974e4d536b4f5c6fe).

It's working when I run master locally, maybe something during the build process is breaking it?

**Comment by vgrichina** [comment]
looks like we collect some events (e.g. when you visit page it's recorded)

somehow we ended up with no `gtag` function though which would explain us not getting explicitt events

**Comment by vgrichina** [comment]
Fixed, minimizer was too aggressive as `gtag` wasn't used anywhere directly (only implicitly through `window.gtag`)
