### ISSUE TITLE
Make all user-visible strings localizable

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-wallet#217]
For now we only do localization for errors in `RequestStatusBox`:
https://github.com/nearprotocol/near-wallet/blob/2e96e2b16572819607e77dd9bc42d1166967bf5c/src/components/common/RequestStatusBox.js#L56

Ideally all strings in our UI should be localizable using https://ryandrewjohnson.github.io/react-localize-redux-docs/ (we can also change the library if there are good reasons to do this).

**Comment by kcole16** [comment]
@vgrichina @marcinbodnar Is this complete as a result of #217?

**Comment by marcinbodnar** [comment]
@kcole16 not yet, this was translations for buttons only.

**Comment by marcinbodnar** [comment]
@kcole16 @vgrichina final part is ready with #455, I did also change indentation for all files.
