### ISSUE TITLE
Update seed phrase copy and add confirmation step

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-wallet#218]
User creates a wallet and wants to manually recover the seed phrase. After going to "I choose to backup my account manually", the user is led to the seed phrase section and asked to take note of their seed phrase.

**The Problem**
The Button in this section states "Setup seed phrase", which implies a form of the setup process. Instead, the user will be led to the wallet home dashboard. 

**Expected Behaviour**
If there is no additional setup process, calling the button "Finished" might be more appropriate. Alternatively, retyping the seed phrase in the next section to ensure that the user took note of the seed phrase might be another option.

**Comment by kcole16** [comment]
"Setup seed phrase" has been confusing to users, will definitely update this copy. 

We're considering a lightweight "Confirm" step, possibly with just a one word confirm ("Please enter the third word of the seed phrase to continue"). @jakestutzman

**Comment by kcole16** [comment]
[Designs](https://projects.invisionapp.com/share/9ES2D82U8GB#/screens/392906893)

### Acceptance Criteria

Setup Seed Phrase
- [ ] User can view their seed phrase
- [ ] Selecting "Copy Phrase" copies seed phrase to the clipboard
- [ ] Selecting "Continue" redirects user to "Verify Seed Phrase" page

Verify
- [ ] User is directed to enter randomized word (# 1-12)
- [ ] User can select "Verify"
  - [ ] If word matches, user is redirect to success page
  - [ ] If word doesn't match, user receives error message "You entered the incorrect word"

- [ ] Tested
- [ ] Mobile ok

**Comment by vgrichina** [comment]
> The Button in this section states "Setup seed phrase", which implies a form of the setup process. Instead, the user will be led to the wallet home dashboard.

just to be clear, it's called like that because seed phrase isn't added to account before you press the button

I like the idea of lightweight verification process, full verification is too annoying.

>  Selecting "Copy Phrase" copies seed phrase to the clipboard

Mixed feeling about this. I wouldn't encourage copying it to clipboard. It's way too easy for spyware to steal stuff from clipboard (no access privileges needed at all usually).

**Comment by kcole16** [comment]
Reasonable point re: copying phrase to clipboard. It's a standard practice to have it (metamask, coinbase wallet, etc), but given it's an opt in for more security-focus in our case, maybe we can exclude it.

**Comment by vgrichina** [comment]
@kcole16 if we don't mess with web layout it should be copy-able by default (just select text and copy) vs desktop/mobile apps where you have to make stuff copy-able.

**Comment by kcole16** [comment]
Closed by #255
