### ISSUE TITLE
Unhelpful error message if trying to create an account with special chars in namee

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-wallet#241]
Steps to repro: 
try to create an account like special.chars.

Expected result:
UI that says that special characters are not allowed. 

What actually happens: 
UI incorrectly says that username is already taken. 

<img width="1395" alt="Screen Shot 2019-11-20 at 2 52 27 PM" src="https://user-images.githubusercontent.com/1320689/69285431-c0c70800-0ba5-11ea-9986-e5fc5062b6f8.png">

**Comment by marcinbodnar** [comment]
@janedegtiareva @kcole16 the idea was not to allow to enter some special chars (if you chose one that is not allowed it will not appear in input). I can see from a repo that we changed text information but didn't change allowed chars in regex (`@` and `.` was allowed before).

@kcole16 want me to change it?

**Comment by kcole16** [comment]
@marcinbodnar Yes, please update the regex. My fault for not changing it when I updated the text.
