### ISSUE TITLE
Update wallet UI to reflect the token units in nearcore

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-wallet#252]
https://github.com/nearprotocol/nearcore/issues/1723
When this change lands in nearcore, we need to update wallet to display token amounts correctly.

**Comment by kcole16** [comment]
@marcinbodnar In which components do we convert from attoNEAR (18 decimal precision) to NEAR?

**Comment by marcinbodnar** [comment]
@kcole16 it's `Balance.js`
https://github.com/nearprotocol/near-wallet/blob/master/src/components/common/Balance.js

**Comment by kcole16** [comment]
Closed by #292
