### ISSUE TITLE
Seed phrase recovery input doesn't allow valid seed phrase

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#256]
**Problem**
I'm receiving a validation error "Please match the requested format" when entering the following seed phrase during recovery. This was the seed phrase generated during the initial setup process.

```assume sad cargo build cake wealth arm maximum people win oil best```

**Steps to reproduce**

1. Go to https://wallet.nearprotocol.com/recover-seed-phrase
2. Enter username ```testkey```
3. Enter the above seed phrase

**Comment by kcole16** [comment]
@vgrichina Thoughts on this? I can't recover any seed phrases currently

**Comment by vgrichina** [comment]
So for this seed phrase there is following public key:

```
ed25519:suVDHUUfiJxtPzrMzdCZjk5qCG27UN2awt12LUa98FU
```

while for account there are different keys:

```
Keys for account testkey
[
  {
    access_key: { nonce: 0, permission: 'FullAccess' },
    public_key: 'ed25519:5w5aR3mmxiSTwWRPJJdbkJLujv6s29rftoEtG5ppv99d'
  },
  {
    access_key: { nonce: 1, permission: 'FullAccess' },
    public_key: 'ed25519:F477BrSfKBFfSySfAxoHNfMgNVeH57smXXwvePnKi4FU'
  }
]
```

I'll try to reproduce with newly created account.

**Comment by vgrichina** [comment]
@kcole16  I've just tried with following account / seed-phrase:


test-seed-phrase

pass demand spike leisure dilemma quarter weasel rabbit air lounge verify humor


Are you sure you've completed seed phrase setup for given account? It's currently only set up after you verify you recorded it.

**Comment by kcole16** [comment]
> Are you sure you've completed seed phrase setup for given account? It's currently only set up after you verify you recorded it.

Positive. This issue is occurring before a request is even sent, so even if the seed phrase wasn't set up, it would be a problem. Sometimes the phrases do validate correctly, but often (50%) they do not. I haven't yet pinpointed the exact issue (have also tried Chrome, Safari, and Firefox). 

Try this phrase on wallet.nearprotocol.com:

username: ```seedtest3```
seed: ```call wall surge job plate census creek memory bomb lift nerve anxiety```

**Comment by vgrichina** [comment]
Try this phrase on wallet.nearprotocol.com:

username: seedtest3
seed: call wall surge job plate census creek memory bomb lift nerve anxiety

This one recovered just fine for me :/

**Comment by kcole16** [comment]
Closing until this can be reproduced
