### ISSUE TITLE
"Receive" option in navbar and standalone page

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#306]
## Acceptance Criteria

- [x] "Receive Tokens" option in the navbar
- [x] User scans QR code and is redirected to ```/send-money/<accountID>```
- [x] Mobile ok
- [x] Tested

## Assets

[Description and mockup](https://www.notion.so/nearprotocol/Wallet-Receive-Money-8ce8106dfd0745fcbb70317786cd4aa9)

**Comment by vgrichina** [comment]
@Patrick1904 @kcole16 let's also add QR scanner in "Send" as most people (in US at least) don't know how to scan QR code.

https://github.com/nimiq/qr-scanner looks good in terms of code size impact. Also most likely https://parceljs.org/code_splitting.html#using-dynamic-imports can be used to reduce impact when it's not needed.
