### ISSUE TITLE
NEAR Account ID example displayed with dot

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-wallet#344]
**Problem**
Not sure whether this is still relevant but the example AccountID displayed in the wallet when signing up includes a name.test

![walletregistrationDot](https://user-images.githubusercontent.com/33576047/72897223-c36ae880-3d21-11ea-92bc-4d69d9a80b46.PNG)

**Expected Behavior**
Thought that names are without the dot; but then, it would be helpful to have the ".test" automatically added to all AccountIDs created in testnet. As a user, I want to have clear visual indicators showing whether I am on testnet or on mainnet. 

**Steps to reproduce**

1. Create a new account on testnet.

**Comment by Patrick1904** [comment]
Removed .test from placeholder as part of https://github.com/nearprotocol/near-wallet/pull/383. Closing.
