### ISSUE TITLE
Need Help div background colour does not match footer background

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-wallet#345]
**Problem**
The background colour of the need help section in the footer does not match the background colour of the footer.

![needhelpdiv](https://user-images.githubusercontent.com/33576047/72898203-eac2b500-3d23-11ea-8eea-b3aaaeadea8f.PNG)

**Expected Behavior**
They should be the same colour

**Steps to reproduce**

1. Open the wallet 
2. Scroll to the bottom

**Comment by marcinbodnar** [comment]
It matches the design.

**Comment by AnaisUrlichs** [comment]
So these are supposed to be different colors? That is confusing

**Comment by marcinbodnar** [comment]
I think it's like a frame, the `Need Help` is gray, so with a white background it's more visible.
https://projects.invisionapp.com/share/9ES2D82U8GB#/screens

**Comment by Patrick1904** [comment]
This is fixed as part of https://github.com/nearprotocol/near-wallet/pull/383/commits. Closing.
