### ISSUE TITLE
Authorize page - layout bug - when screen size is limited, buttons disappear

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-wallet#36]
see sreenshot

**Comment by janedegtiareva** [comment]
<img width="1399" alt="Screen Shot 2019-05-14 at 2 53 32 PM" src="https://user-images.githubusercontent.com/1320689/57735096-595d5800-7658-11e9-85d6-7ecee9be1af1.png">

**Comment by kcole16** [comment]
Looks like this is fixed now?
