### ISSUE TITLE
signup: Incorrect error message for blank username

### ISSUE THREAD

**Issue by chadoh** [nearprotocol/near-wallet#362]
## Problem
When initially creating account,
if you enter text and then delete it,
then you see an error that says "username is taken"

Screen recording:

![incorrect error message for empty username 2020-01-29 at 11 00 17](https://user-images.githubusercontent.com/221614/73373600-e566ec80-4286-11ea-9bd9-d0ad3f6fb508.gif)

## Expected Behavior

Does some account on testnet actually have `""` as a username?

Regardless, it should probably say something like "username cannot be blank," or just reset to the initial state.

## Similar to

Maybe this could be considered part of #79 or #241

**Comment by Patrick1904** [comment]
This was fixed as part of https://github.com/nearprotocol/near-wallet/pull/383. Closing.
