### ISSUE TITLE
signup: email confirmation page takes a while

### ISSUE THREAD

**Issue by chadoh** [nearprotocol/near-wallet#363]
## Steps to reproduce

1. Sign up for a new account
2. Enter email
3. Form submits, shows loading state

## Problem

4. The page goes back to looking like it did before you submitted the form. It hangs for a couple seconds. Then, just as you start wondering if you need to click "submit" again, the "Confirm Recovery Setup" page shows up.

## Expected Behavior

4. Right after the "submitting" state ends on the form, you get redirected to the "Confirm Recovery Setup" page.

**Comment by kcole16** [comment]
@chadoh I believe this is a duplicate of #356

**Comment by chadoh** [comment]
Yes, thanks!
