### ISSUE TITLE
Prevent user from deleting last full access key from their account

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-wallet#406]
**Problem**
User by mistake or from misunderstanding might try to remove the full access key that they are accessing this account with.
Similar true about their recovery key.

**Expected Behavior**
Prevent or have a "danger" message with confirmation for deleting full access key and especially the one that is currently active in the wallet and recovery key.

**Comment by vgrichina** [comment]
@kcole16 @ilblackdragon @Patrick1904  let's have the "type your account name" guard (similar to how dangerous transactions are confirmed) for removing the key owned by current wallet.

**Comment by kcole16** [comment]
I think we should remove the "Full Access Key" section entirely once recovery management and multi-device support are live. 

If users want to remove a device key (only in localStorage), they should have to do it from a different device. Alternatively, we could allow them to delete the current device key, but only by creating a new key first.

**Comment by ilblackdragon** [comment]
Agree with @kcole16 
 @vgrichina what you suggesting we should add to "delete account" functionality: enter beneficiary and then confirm that you know what you are doing (that all of your assets won't actually end up there, unless you transfer them manually first for exmaple). Not sure we should expose this any time soon though.

**Comment by kcole16** [comment]
Closed by #486

**Comment by kcole16** [comment]
User is now prevented from deleting their last full access key on their current device. This will be optimized in #422
