### ISSUE TITLE
Warning on create account - recover account

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/near-wallet#41]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in CreateAccount (created by Context.Consumer)
    in Connect(CreateAccount) (created by Context.Consumer)

**Comment by eriktrautman** [comment]
How should we classify/label this? Is it considered a bug?
