### ISSUE TITLE
Phone recovery is not sending text, new account unrecoverable

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/near-wallet#421]
**Problem**
A user tries to use the phone recovery method when creating a new account. The newly created account becomes unrecoverable.

**Expected Behavior**
A text message is sent, or on failure a new recovery method is required so that the user can recover the account at a later time.

**Steps to reproduce**
1. Visit https://wallet.nearprotocol.com/create
2. Create a new account
3. Select phone recovery
4. Enter phone number and click/tap button to protect account
5. Notice that it didn't send a text, notice that the console errors show it did not succeed.

<img width="674" alt="Screenshot 2020-02-27 11 54 51" src="https://user-images.githubusercontent.com/1042667/75482067-ec058400-5958-11ea-8e14-6cf5d09f4790.png">

**Comment by Patrick1904** [comment]
@vgrichina are you aware of any recent changes breaking this?

**Comment by vgrichina** [comment]
@Patrick1904 I'll take a look right now

**Comment by vgrichina** [comment]
This is fixed. Render config needed update for Twilio.
