### ISSUE TITLE
Copy URL does not work

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-wallet#448]
**Problem**
When clicking "Copy URL" the URL isn't copied to my clipboard.

**Expected Behavior**
The URL should be copied to the clipboard when a user tries to restore their account
![walletproblem](https://user-images.githubusercontent.com/33576047/76764770-b56f9c00-6795-11ea-8482-36f2c6d1e6fb.png)

Note this might be a Windows-specific problem. The problem came up on Windows 10 NT, Firefox 74.0 (64-bit)

**Comment by kcole16** [comment]
@Patrick1904 Reproduced on Mac using Firefox 74.0

Pretty sure it's a Firefox thing. Works on Chrome and Safari.
