### ISSUE TITLE
Devnet/betanet uses wrong Explorer backend "link" to query activity

### ISSUE THREAD

**Issue by frol** [nearprotocol/near-wallet#453]
Currently, the WAMP function name is hard-coded and references testnet, while it has to be different for the different networks:

https://github.com/nearprotocol/near-wallet/blob/397279c7cfa0a03f053a65ac83e9997d0460c0f9/src/utils/explorer-api.js#L12

Make the network name configurable and use `devnet` / `betanet` instead of `testnet` for the relevant configurations.

**Steps to reproduce**

1. Try sending NEAR anywhere from https://wallet.devnet.nearprotocol.com/
2. Go back to the dashboard
3. There are no activities or activities from the testnet (if your account id matches the one existing on testnet)

**Comment by kcole16** [comment]
This appears to be fixed? @vgrichina
