### ISSUE TITLE
Wallet allows creation of account names less than 5 characters

### ISSUE THREAD

**Issue by dantrevino** [nearprotocol/near-wallet#474]
**Problem**
Wallet documentation 
https://docs.nearprotocol.com/docs/local-setup/create-account
and wallet app
https://wallet.nearprotocol.com
both indicate a minimum account length of 5 characters.  I was able to create accounts with length 2, 3, and 4 characters.

**Expected Behavior**

Account names less than 5 characters should be rejected.

**Steps to reproduce**

1. Go to https://wallet.nearprotocol.com 
2. Create an account with 2, 3, or 4 characters.

![image](https://user-images.githubusercontent.com/7738/77566596-22b0ba80-6e83-11ea-83c8-60d49bcd2918.png)

**Comment by kcole16** [comment]
Thanks @dantrevino! Moving this issue to the docs repo, as we currently do allow shorter names in the wallet intentionally (above 2 characters).

We're deploying some changes soon (#407) that will disallow the creation of top-level domain names (e.g. `dan`) and instead create a subdomain, which will be based on the network (`dan.testnet` for TestNet, `dan.near` for MainNet).

**Comment by kcole16** [comment]
Issue moved to [nearprotocol/docs #281](https://github.com/nearprotocol/docs/issues/281) via [**ZenHub**](https://www.zenhub.com/)
