### ISSUE TITLE
Send tokens to user

### ISSUE THREAD

**Issue by eriktrautman** [nearprotocol/near-wallet#49]
As a user logged into my account on the web wallet, I want to send 100 tokens to another existing user so I can pay them back for that Bitcoin Pizza.

## Acceptance Criteria

- [ ] Can send tokens between accounts that exist
- [ ] Proper error handling and user-informing for cases where account doesn't exist
- [ ] Updates balance of recipient user immediately upon refreshing their browser
- [ ] ??? Include "Add a note..." field?

## Assets

- Sparse mockup: https://projects.invisionapp.com/share/9ES2D82U8GB#/screens/363859416
- Full mockup (includes extra features): https://projects.invisionapp.com/share/Y5QIVUGTVER#/screens/362044982

**Comment by vgrichina** [comment]
>  Updates balance of recipient user immediately upon refreshing their browser

Shouldn't it better be "without refreshing their browser"? This will also force us to implement event subscriptions in nearcore/nearlib which is highly desired feature by a lot of blockchain devs we talked with.

**Comment by vgrichina** [comment]
>  ??? Include "Add a note..." field?

there is AFAIK no such field at `nearcore` level.
@ilblackdragon what are `nearcore` plans on this?

**Comment by bowenwang1996** [comment]
We could do that if really necessary. However, I feel like we probably don't want to put that information on chain as it will be public.

**Comment by eriktrautman** [comment]
> Shouldn't it better be "without refreshing their browser"? This will also force us to implement event subscriptions in nearcore/nearlib which is highly desired feature by a lot of blockchain devs we talked with.

Definitely agree. Also seems out of scope for this particular story, though.  Maybe the simplest start for this is set up polling the account balance on a decreasing rate after the send is done, eg. 100ms, 200ms, 300ms, 500ms, 800ms... fibonacci or 2^N scheme.

**Comment by vgrichina** [comment]
> However, I feel like we probably don't want to put that information on chain as it will be public.

I think we need to be very explicit not just about that, but that all payments info is actually public. Arguably amount, sender and receiver is even more important info than note. Cause e.g. only complete idiot would actually enter some compromising note like "drugs" or "bribe" :D, but metadata leak is still a problem.

**Comment by vgrichina** [comment]
@eriktrautman there is no need to poll, we can refresh account after every successful transaction made through wallet.
However this won't cover cases when e.g. money is sent to you. Plus it's going to be extra work if we going to implement proper events later. 

So I think main question here is how far we are from having events. @frol when do you think we'll be able to subscribe to given account updates via web sockets?

**Comment by frol** [comment]
@vgrichina I am working on NEAR Explorer side of things now, which has its own websocket server. Do you expect WebSocket connection to nearcore or to explorer? The account info is the part of the second milestone, and I am currently working on getting the frontend and the intermediate backend bootstrapped. Given I plan to complete the first milestone by the next Monday, my ETA is: not earlier than in two weeks.
