### ISSUE TITLE
Activity on homepage doesn't match explorer 

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-wallet#492]
**Problem**

Activity on homepage doesn't match explorer for account created through linkdrop:
https://explorer.nearprotocol.com/accounts/test-linkdrop

**Expected Behavior**

Activity in explorer and wallet is the same

**Steps to reproduce**

1. Create new account using linkdrop URL.
2. Observe absence of activity on homepage.
3. Click "View All" to see activity in explorer (it's not empty now)

**Comment by frol** [comment]
We extracted Actions into a separate table on Explorer (https://github.com/nearprotocol/near-explorer/pull/224), so you need to update the query to JOIN `actions` table. Let us know if you need help with the query.

/cc @icerove
