### ISSUE TITLE
Some forms don't submit when "Enter" is pressed on keyboard

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-wallet#493]
**Problem**

Some forms don't submit when "Enter" is pressed on keyboard

**Expected Behavior**

Enter submits all forms 

**Steps to reproduce**

Try to do anything requiring account name confirmation dialog (e.g. login with full access). Most likely other forms are affected too.

**Comment by kcole16** [comment]
Did a quick audit of this, and appears to only affect https://wallet.nearprotocol.com/login/confirm
