### ISSUE TITLE
TXs in Activity Feed displaying incorrectly

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#519]
**Problem**
The activity feed appears to have a few issues (possibly a result of #466). 
- The timestamp always displays "Just now", even for TXs confirmed days/weeks ago
- Failed TXs are displayed

**Expected Behavior**
- Timestamps should reflect the time since the TX confirmed
- Only successful TXs should show in Activity Feed (for now)

**Steps to Reproduce**
1. Go to wallet.nearprotocol.com (use an existing account)
2. Check the timestamp
3. Click "View All" and compare timestamps between Explorer and Wallet

**Comment by kcole16** [comment]
@vgrichina @Patrick1904 @marcinbodnar 

What are your thoughts re: displaying Failed TXs in the wallet? Currently, we do not show the status, so all TXs in the Activity Feed are implied to be successful.

I think it's ideal to display all TXs, including failed ones. Though until we have more info to display re: the reason for failure (and considering some history may be missing when a TX fails and isn't included in a block), might make more sense to include only successful and pending TXs.

**Comment by Patrick1904** [comment]
> might make more sense to include only successful and pending TXs
I like this. I think we should consider a filter dropdown btn. Default can be to hide failed TXs but user can click the dropdown and select to include failed TXs, etc.

**Comment by marcinbodnar** [comment]
IMO we should display exactly the same transactions that are displayed in explorer, it might be misleading for a user, if he clicks `VIEW ALL` and sees a different list of transactions. 

If we would like to hide failed transactions we can use switcher, instead of a dropdown to show all/succeded. It was designed for explorer (https://projects.invisionapp.com/share/NHQIS41UW62#/screens/354347466) and it's available in Wallet in `ShowingSwitcher` component.

**Comment by marcinbodnar** [comment]
@kcole16 At this moment transactions are not displayed in explorer and wallet, some bug?

**Comment by kcole16** [comment]
@marcinbodnar Explorer was down yesterday due to testnet upgrade. Back up now.

The switcher is a good potential option. We should consider a redesign of the Activity Feed before implementing #456 (tokens), and toggling between TX statuses might fit well there.

In the meantime, should at least add the TX status before the timestamp, as currently users will be unable to distinguish between successful and failed TXs.

**Explorer example:**
<img width="131" alt="Screen Shot 2020-04-15 at 2 40 51 PM" src="https://user-images.githubusercontent.com/5624527/79391861-2c2fbe80-7f27-11ea-9875-74b6e0d84622.png">

(we should exclude the TX hash)

**Comment by marcinbodnar** [comment]
@kcole16 ok, got it.

**Comment by vgrichina** [comment]
I think it also makes sense to color code Failed/Succeeded/Pending statuses.

**Comment by marcinbodnar** [comment]
ok, will do

**Comment by vgrichina** [comment]
@kcole16 I assume we can consider this resolved, right?
