### ISSUE TITLE
Email recovery can have broken link with "undefined"

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/near-wallet#524]
**Problem**

<img width="766" alt="Screenshot 2020-04-16 18 17 24" src="https://user-images.githubusercontent.com/1042667/79521721-b3a42d00-800e-11ea-870a-d165d43dc368.png">

When signing up for an account with a different network (like betanet), the wallet address is:
https://wallet.betanet.nearprotocol.com/
Sign up for an account, choose email as the recovery method.
Note that the email comes in with:
- no indication that it's from a different network (same subject, body)
- broken link to recover the account

**Expected Behavior**
An email comes in letting me know which network this account belongs to, and the recovery link resolves.

**Comment by Patrick1904** [comment]
@chadoh I believe we had this same issue with render domain? Do you remember the fix?

**Comment by mikedotexe** [comment]
@vgrichina made some changes (I think to config or another repo as I don't see commits in this repo) that have fixed this issue. Closing. Thanks, all
