### ISSUE TITLE
Configure .testnet Wallet URL and handle key transfer

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#532]
### Overview

Once mainnet phase 0 launches, users are more likely to get confused with wallet.nearprotocol.com, and eventually will need to use that domain to access the Mainnet version of wallet (especially re: keys in localstorage).

Keys will also still be scoped to the original domain, and will need to be transferred from `wallet` to `wallet.testnet`. 

### Proposed Flow
1. User navigates to `wallet.nearprotocol.com`
2. Check if user has keys in localStorage
  a. No, proceed to Step 3
  b. Yes, include each key and account as URL params
3. Redirect user to `wallet.testnet.nearprotocol.com`
4. For each account
  a. Generate a new access key
  b. Remove original access key 
  c. Store new key in localStorage
     

### Acceptance Criteria

- [ ] Users with TestNet accounts are redirected to from wallet.nearprotocol.com to wallet.testnet.nearprotocol.com
- [ ] Keys are transferred to the proper localStorage domain scope (wallet -> wallet.testnet)

**Comment by marcinbodnar** [comment]
> b. Yes, include each key and account as URL param

@vgrichina maybe a better idea would be to use `postMessage` with `iframe`?

**Comment by kcole16** [comment]
Closing for now, as we aren't currently planning to do this (though may bring back if we get a lot of user requests)
