### ISSUE TITLE
Stake amount is displayed in yoctoNEAR

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-wallet#538]
**Problem**
The stake amount is displayed in yoctoNEAR
<img width="715" alt="Screen Shot 2020-04-24 at 7 48 29 PM" src="https://user-images.githubusercontent.com/5624527/80269923-00b87c80-8669-11ea-95c0-7167bcb71339.png">

**Expected Behavior**
Should be displayed in NEAR (using near-api-js.utils.formatNearAmount() )

**Comment by marcinbodnar** [comment]
@kcole16 @Patrick1904 To test it locally you can change accountId in SQL query, and put accountId for the user that already has staked transaction. 
Change this line:
https://github.com/nearprotocol/near-wallet/blob/master/src/utils/explorer-api.js#L11
to `if (!accountId) accountId = 'oligarr.test'`

Here is explorer link for this user account to compare:
https://explorer.nearprotocol.com/accounts/oligarr.test
