### ISSUE TITLE
Authorize specific transfer transaction in app

### ISSUE THREAD

**Issue by eriktrautman** [nearprotocol/near-wallet#56]
As a user of an app where the app is requesting to initiate a transfer of tokens operation, I want to be able to examine and approve this transaction.

## Acceptance Criteria

- [ ] App can request token transfer transaction
- [ ] Transfer debits and credits tokens properly
- [ ] Wallet redirects to approval flow
- [ ] Flow redirects back to app when complete
- [ ] Mobile views ok
- [ ] Sad path: User denies request
- [ ] Error handling: App formats request improperly
- [ ] Tested

## Assets

- Mockup: cc @jakestutzman 
- [ ] **TODO:** Figure out display of gas fees
- [ ] **TODO:** Figure out interaction of user with gas fees
- [ ] **TODO:** Figure out display of waiting statuses for inclusion in block -- eg sent, received (in mempool), included, waiting (congestion), etc.

**Comment by eriktrautman** [comment]
Testing @jakestutzman @ mention

**Comment by vgrichina** [comment]
This also has to work for multiple transactions at once and not only for token transfer.

**Comment by kcole16** [comment]
Replaced by #147
