### ISSUE TITLE
Wallet does not work with near-ops

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-wallet#70]
To reproduce:
* Get the recent version of near-ops:
```
git clone https://github.com/nearprotocol/near-ops
```
* Start the node (It will take ~10-20 minutes since we are running for the first time from a clean folder):
```
./run_local_dev.sh
```
* Open studio http://localhost and make sure the Hello World contract is working (it makes sure the fiddle api has started which takes long time).
* Open "Example of NEAR Wallet Integration" and try running it. Get the following error message:
https://www.dropbox.com/s/ac0r8dgnesi1txo/Screenshot%202019-06-05%2009.49.17.png?dl=0

**Comment by vgrichina** [comment]
This likely isn't related to wallet. The issue is about loading `gulp-utils`, which is used for compilation of every project. Did you try hello world example?

**Comment by nearmax** [comment]
Hello work example works.

**Comment by vgrichina** [comment]
@nearmax this is super weird, do you have live demo anywhere?

**Comment by nearmax** [comment]
I don't but you can reproduce it yourself following the above instructions.

**Comment by vgrichina** [comment]
I think your issue got fixed here https://github.com/nearprotocol/NEARStudio/commit/6b1e662a66a9178953ed6b1fdaf6367de1390994
