### ISSUE TITLE
Storage fees in wallet

### ISSUE THREAD

**Issue by eriktrautman** [nearprotocol/near-wallet#74]
This is deeper than meets the eye and includes everything related to dealing with storage fees.

+ Displaying storage fees in the wallet in a way that users clearly understand how they work and why exactly they are being charged.
+ Handling what happens when the user's account doesn't have sufficient tokens to pay for their storage -- how do we show the account has been "sleeped" and then recover it later once more tokens have been added?

**Comment by kcole16** [comment]
Closing now that we've switched to state staking (covered in #481 )
