### ISSUE TITLE
After "Login with NEAR" is done, should return back to proper url

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-wallet#98]
Currently we get back to URL witch contains callback data: `https://near-fiddle-api.onrender.com/app/psnm1mjqq/?account_id=illia.china&public_key=APxuLm5U4KNebBzeZNP6qojNj6z3kCeCD1iPPJmCqWWB`
We should after accepting this data, rewrite URL to remove this.

**Comment by kcole16** [comment]
Looks like this is fixed? Closing for now (will reopen if not)

**Comment by vgrichina** [comment]
@kole16 how did you test this?
